import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Iliad Social Spark',
};

export function TermsOfServiceContent() {
  return (
    <>
      <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using Iliad Social Spark (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you may not access the Service. Access is restricted to authorized users with an "@iliadmg.com" email address.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Iliad Social Spark is an AI-powered toolkit designed to assist with social media marketing tasks, including audience analysis, strategy development, content creation, and scheduling. The Service utilizes third-party generative AI models to produce content based on user inputs.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        To use the Service, you must register for an account using Google Sign-In. You are responsible for safeguarding your account and for any activities or actions under your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
      </p>

      <h2>4. User Conduct and Responsibilities</h2>
      <p>
        You agree not to use the Service to:
      </p>
      <ul>
        <li>Generate, upload, or transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
        <li>Generate content that infringes upon any third party's intellectual property rights, including copyright, trademark, or patent.</li>
        <li>Attempt to gain unauthorized access to the Service, other accounts, or computer systems or networks connected to the Service.</li>
        <li>Use the Service for any purpose other than its intended use as a social media marketing toolkit.</li>
      </ul>
      <p>You are solely responsible for the content you generate and its use. We are not responsible for the accuracy, appropriateness, or legality of the content generated by the AI on your behalf.</p>


      <h2>5. Intellectual Property</h2>
      <p>
        The Service and its original content (excluding content generated by you), features, and functionality are and will remain the exclusive property of The Calton Group and its licensors. The content you generate ("User-Generated Content") remains your property. However, by using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and transmit your input data to provide the Service to you.
      </p>

      <h2>6. Termination</h2>
      <p>
        We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
      </p>

      <h2>7. Disclaimer of Warranties</h2>
      <p>
        The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the accuracy, reliability, or completeness of the content generated by the Service. Your use of the Service is at your sole risk.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        In no event shall The Calton Group, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
      </p>
      
      <h2>9. Governing Law</h2>
      <p>
        These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which The Calton Group operates, without regard to its conflict of law provisions.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.
      </p>
      
      <h2>11. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us at: <a href="mailto:darrell@iliadmg.com">darrell@iliadmg.com</a>
      </p>
    </>
  );
}
