import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Iliad Social Spark',
};

export default function PrivacyPage() {
  return (
    <>
      <h1>Privacy Policy for Iliad Social Spark</h1>
      <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

      <h2>Introduction</h2>
      <p>
        Welcome to Iliad Social Spark ("we," "our," or "us"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application.
      </p>
      <p>
        By using Iliad Social Spark, you agree to the collection and use of information in accordance with this policy.
      </p>

      <h2>Information We Collect</h2>
      <p>
        We may collect information about you in a variety of ways. The information we may collect via the Application includes:
      </p>
      
      <h3>Personal Data</h3>
      <p>
        When you register and log in using Google Sign-In, we collect personal information that you provide to Google, such as your name and email address. This information is used solely for the purpose of identifying you as a user within our system and securing your account. We only permit users with an email address ending in "@iliadmg.com" to access the service.
      </p>

      <h3>User-Generated Content</h3>
      <p>
        We collect and store the data you provide to the application, including brand details, target demographics, and any other inputs you submit to our AI tools ("Client Journeys"). We also store the content generated by the AI on your behalf. This data is necessary for the core functionality of the application and to allow you to save and resume your work.
      </p>

      <h2>Use of Your Information</h2>
      <p>
        Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Application to:
      </p>
      <ul>
        <li>Create and manage your account.</li>
        <li>Authenticate your access to the application.</li>
        <li>Store and retrieve your work (Client Journeys).</li>
        <li>Send your inputs to third-party generative AI APIs (such as Google's Gemini) to produce the content you request.</li>
        <li>Provide you with user support. Contact us at darrell@iliadmg.com.</li>
      </ul>

      <h2>Disclosure of Your Information</h2>
      <p>
        We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties. Your information may be disclosed under the following circumstances:
      </p>
      <ul>
        <li><strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.</li>
        <li><strong>Third-Party Service Providers:</strong> We use Google Firebase for authentication and database storage, and Google's Generative AI models (Gemini) for content generation. These services have their own privacy policies, and we encourage you to review them. Your inputs will be sent to these AI services to generate outputs.</li>
      </ul>

      <h2>Security of Your Information</h2>
      <p>
        We use administrative, technical, and physical security measures to help protect your personal information. We utilize Google Cloud Firebase, which provides robust security for data storage and authentication. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
      </p>

      <h2>Data Retention</h2>
      <p>
        We will retain your Personal Data and User-Generated Content only for as long as is necessary for the purposes set out in this Privacy Policy, or to comply with our legal obligations.
      </p>

      <h2>Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have questions or comments about this Privacy Policy, please contact us at: <a href="mailto:darrell@iliadmg.com">darrell@iliadmg.com</a>
      </p>
    </>
  );
}